require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlunoDisciplinasController do

  # This should return the minimal set of attributes required to create a valid
  # AlunoDisciplina. As you add validations to AlunoDisciplina, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "aluno" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlunoDisciplinasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aluno_disciplinas as @aluno_disciplinas" do
      aluno_disciplina = AlunoDisciplina.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aluno_disciplinas).should eq([aluno_disciplina])
    end
  end

  describe "GET show" do
    it "assigns the requested aluno_disciplina as @aluno_disciplina" do
      aluno_disciplina = AlunoDisciplina.create! valid_attributes
      get :show, {:id => aluno_disciplina.to_param}, valid_session
      assigns(:aluno_disciplina).should eq(aluno_disciplina)
    end
  end

  describe "GET new" do
    it "assigns a new aluno_disciplina as @aluno_disciplina" do
      get :new, {}, valid_session
      assigns(:aluno_disciplina).should be_a_new(AlunoDisciplina)
    end
  end

  describe "GET edit" do
    it "assigns the requested aluno_disciplina as @aluno_disciplina" do
      aluno_disciplina = AlunoDisciplina.create! valid_attributes
      get :edit, {:id => aluno_disciplina.to_param}, valid_session
      assigns(:aluno_disciplina).should eq(aluno_disciplina)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlunoDisciplina" do
        expect {
          post :create, {:aluno_disciplina => valid_attributes}, valid_session
        }.to change(AlunoDisciplina, :count).by(1)
      end

      it "assigns a newly created aluno_disciplina as @aluno_disciplina" do
        post :create, {:aluno_disciplina => valid_attributes}, valid_session
        assigns(:aluno_disciplina).should be_a(AlunoDisciplina)
        assigns(:aluno_disciplina).should be_persisted
      end

      it "redirects to the created aluno_disciplina" do
        post :create, {:aluno_disciplina => valid_attributes}, valid_session
        response.should redirect_to(AlunoDisciplina.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aluno_disciplina as @aluno_disciplina" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlunoDisciplina.any_instance.stub(:save).and_return(false)
        post :create, {:aluno_disciplina => { "aluno" => "invalid value" }}, valid_session
        assigns(:aluno_disciplina).should be_a_new(AlunoDisciplina)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlunoDisciplina.any_instance.stub(:save).and_return(false)
        post :create, {:aluno_disciplina => { "aluno" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aluno_disciplina" do
        aluno_disciplina = AlunoDisciplina.create! valid_attributes
        # Assuming there are no other aluno_disciplinas in the database, this
        # specifies that the AlunoDisciplina created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlunoDisciplina.any_instance.should_receive(:update).with({ "aluno" => "" })
        put :update, {:id => aluno_disciplina.to_param, :aluno_disciplina => { "aluno" => "" }}, valid_session
      end

      it "assigns the requested aluno_disciplina as @aluno_disciplina" do
        aluno_disciplina = AlunoDisciplina.create! valid_attributes
        put :update, {:id => aluno_disciplina.to_param, :aluno_disciplina => valid_attributes}, valid_session
        assigns(:aluno_disciplina).should eq(aluno_disciplina)
      end

      it "redirects to the aluno_disciplina" do
        aluno_disciplina = AlunoDisciplina.create! valid_attributes
        put :update, {:id => aluno_disciplina.to_param, :aluno_disciplina => valid_attributes}, valid_session
        response.should redirect_to(aluno_disciplina)
      end
    end

    describe "with invalid params" do
      it "assigns the aluno_disciplina as @aluno_disciplina" do
        aluno_disciplina = AlunoDisciplina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlunoDisciplina.any_instance.stub(:save).and_return(false)
        put :update, {:id => aluno_disciplina.to_param, :aluno_disciplina => { "aluno" => "invalid value" }}, valid_session
        assigns(:aluno_disciplina).should eq(aluno_disciplina)
      end

      it "re-renders the 'edit' template" do
        aluno_disciplina = AlunoDisciplina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlunoDisciplina.any_instance.stub(:save).and_return(false)
        put :update, {:id => aluno_disciplina.to_param, :aluno_disciplina => { "aluno" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aluno_disciplina" do
      aluno_disciplina = AlunoDisciplina.create! valid_attributes
      expect {
        delete :destroy, {:id => aluno_disciplina.to_param}, valid_session
      }.to change(AlunoDisciplina, :count).by(-1)
    end

    it "redirects to the aluno_disciplinas list" do
      aluno_disciplina = AlunoDisciplina.create! valid_attributes
      delete :destroy, {:id => aluno_disciplina.to_param}, valid_session
      response.should redirect_to(aluno_disciplinas_url)
    end
  end

end
